### ISSUE TITLE
ConfigParser crashes during pasing moonlight config

### ISSUE THREAD

**Issue by tibersam** [veldenb/plugin.program.moonlight-qt#24]
Hi all,

I am having the problem, that moonlight is crashing during starting once configured (e.g. I ran it successfully and configured moonlight, then it crashed when i tried to launch the plugin again.)

From the log the error was:
2022-09-11 19:35:01.376 T:1415    ERROR <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'configparser.InterpolationSyntaxError'>
                                                   Error Contents: '%' must be followed by '%' or '(', found: '%)'
                                                   Traceback (most recent call last):
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 227, in <module>
                                                       show_gui(addon_handle, page_mode, page_host_id, page_game_id)
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 150, in show_gui
                                                       hosts = get_moonlight_config().get('hosts')
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 52, in get_moonlight_config
                                                       return parse_moonlight_config(moonlight_full_config_path)
                                                     File "/storage/.kodi/addons/plugin.program.moonlight-qt/addon.py", line 65, in parse_moonlight_config
                                                       optionValue = config.get(section, option)
                                                     File "/usr/lib/python3.8/configparser.py", line 799, in get
                                                     File "/usr/lib/python3.8/configparser.py", line 395, in before_get
                                                     File "/usr/lib/python3.8/configparser.py", line 442, in _interpolate_some
                                                   configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%)'
                                                   -->End of Python script error report<--

The line that propably produced the error in the moonlight.conf file was the following:
1\mac=@ByteArray(*******%)
(Note: I censored the first 8 characters and replaced them with * as they are probably not relevant.)
As i understand it this is a file produced by moonlight itself, so editing is no option.
My fix was to Replace ConfigParser with RawConfigParser in addon.py line 56.
Now it is at least running again and i can launch Moonlight again. 

My question is, was this the right solution to the problem? 
Should i make a pull request?

Also note when upgrading to > Python 3.2 this is the new way forwared (https://stackoverflow.com/questions/14340366/configparser-and-string-with):
configParser = configparser.ConfigParser(interpolation=None)

**Comment by veldenb** [comment]
Hi @tibersam

I added a commit to disable the interpolation: ab4e04cc0202da39ee65dccbcd11db4932a8d36a

I still have to test it but I think it's ok :)
Thanks for debugging the problem, the fix will be in the next release.

**Comment by veldenb** [comment]
Tested, seems to work without a problem.
