### ISSUE TITLE
Kodi 20+ missing addon under 'Games' section in main menu

### ISSUE THREAD

**Issue by kurac338** [veldenb/plugin.program.moonlight-qt#34]
After updating to OSMC v2023.06-1 (Kodi v20.1) the v3.0.0 of this plugin is no longer listed in the main menu 'Games' section.
A workaround is to add the addon under the favorites section and launch it from there.
Most probably Kodi changed the addon configuration requirements since v20+?

**Comment by veldenb** [comment]
I'm not sure, could this be a OSMC issue? Under LibreELEC and Ubuntu I get an icon under the Games section:
![afbeelding](https://github.com/veldenb/plugin.program.moonlight-qt/assets/33846360/7cdd7408-614c-4ffe-800a-e5441123d964)

**Comment by kurac338** [comment]
I can see the same on OSMC as in your screenshot.
However "opening" the plugin using the icon from the screenshot does not open the addon (at least on OSMC).
So you need to enter the "Games" section, and inside of that submenu, its no longer visible.

**Comment by veldenb** [comment]
Can you try to open the Moonlight menu and send your `~/.kodi/temp/kodi.log`?

**Comment by kurac338** [comment]
Sure, here it is:
``` log
﻿2023-06-24 16:50:29.008 T:554      info <general>: -----------------------------------------------------------------------
2023-06-24 16:50:29.008 T:554      info <general>: Starting Kodi (20.1). Platform: Linux ARM (Thumb) 32-bit
2023-06-24 16:50:29.008 T:554      info <general>: Using Release Kodi x32
2023-06-24 16:50:29.008 T:554      info <general>: Kodi compiled 2023-06-03 by GCC 10.2.1 for Linux ARM (Thumb) 32-bit version 5.15.83 (331603)
2023-06-24 16:50:29.008 T:554      info <general>: Running on BCM2835 with Open Source Media Center 2023.06-1, kernel: Linux ARM 32-bit version 5.15.83-2-osmc
2023-06-24 16:50:29.032 T:554      info <general>: FFmpeg version/source: ce5ef77-kodi-4.4.1-Nexus-Alpha1
2023-06-24 16:50:29.032 T:554      info <general>: 4 CPU cores available
2023-06-24 16:50:29.032 T:554      info <general>: ARM Features: Neon disabled
2023-06-24 16:50:29.032 T:554      info <general>: special://xbmc/ is mapped to: /usr/share/kodi
2023-06-24 16:50:29.032 T:554      info <general>: special://xbmcbin/ is mapped to: /usr/lib/kodi
2023-06-24 16:50:29.032 T:554      info <general>: special://xbmcbinaddons/ is mapped to: /usr/lib/kodi/addons
2023-06-24 16:50:29.032 T:554      info <general>: special://masterprofile/ is mapped to: /home/osmc/.kodi/userdata
2023-06-24 16:50:29.032 T:554      info <general>: special://envhome/ is mapped to: /home/osmc
2023-06-24 16:50:29.032 T:554      info <general>: special://home/ is mapped to: /home/osmc/.kodi
2023-06-24 16:50:29.033 T:554      info <general>: special://temp/ is mapped to: /home/osmc/.kodi/temp
2023-06-24 16:50:29.033 T:554      info <general>: special://logpath/ is mapped to: /home/osmc/.kodi/temp
2023-06-24 16:50:29.033 T:554      info <general>: Webserver extra whitelist paths:
2023-06-24 16:50:29.033 T:554      info <general>: The executable running is: /usr/lib/kodi/kodi.bin
2023-06-24 16:50:29.033 T:554      info <general>: Local hostname: osmc
2023-06-24 16:50:29.033 T:554      info <general>: Log File is located: /home/osmc/.kodi/temp/kodi.log
2023-06-24 16:50:29.033 T:554      info <general>: -----------------------------------------------------------------------
2023-06-24 16:50:29.050 T:554      info <general>: loading settings
2023-06-24 16:50:29.052 T:554      info <general>: special://profile/ is mapped to: special://masterprofile/
2023-06-24 16:50:29.072 T:554      info <general>: Loaded settings file from special://xbmc/system/advancedsettings.xml
2023-06-24 16:50:29.072 T:554      info <general>: Contents of special://xbmc/system/advancedsettings.xml are...
                                                   <?xml version="1.0" encoding="UTF-8" ?>
                                                   <!-- Do not modify! These are OSMC Optimised Settings for your device  !-->
                                                   <!-- If you wish to override any of these values, then create a file in /home/osmc/.kodi/userdata/advancedsettings.xml !-->
                                                   <!-- It will override these settings, and your settings will be preserved across OSMC updates !-->
                                                   <advancedsettings version="1.0">
                                                     <imageres>540</imageres>
                                                     <fanartres>720</fanartres>
                                                     <splash>false</splash>
                                                     <handlemounting>0</handlemounting>
                                                     <samba>
                                                       <clienttimeout>30</clienttimeout>
                                                     </samba>
                                                     <cputempcommand>/bin/sed -e &apos;s/\([0-9]*\)[0-9]\{3\}.*/\1 C/&apos; /sys/class/thermal/thermal_zone0/temp</cputempcommand>
                                                     <gputempcommand>/bin/sed -e &apos;s/\([0-9]*\)[0-9]\{3\}.*/\1 C/&apos; /sys/class/thermal/thermal_zone0/temp</gputempcommand>
                                                     <gamesgeneral>
                                                       <enable>true</enable>
                                                     </gamesgeneral>
                                                     <videoscreen>
                                                       <screen>0</screen>
                                                     </videoscreen>
                                                     <myvideos>
                                                       <usetags>false</usetags>
                                                     </myvideos>
                                                   </advancedsettings>

2023-06-24 16:50:29.078 T:554      info <general>: Loaded settings file from special://profile/advancedsettings.xml
2023-06-24 16:50:29.078 T:554      info <general>: Contents of special://profile/advancedsettings.xml are...
                                                        < REDACTED >

2023-06-24 16:50:29.078 T:554   warning <general>: VIDEO database configuration is experimental.
2023-06-24 16:50:29.078 T:554   warning <CSettingsManager>: missing version attribute
2023-06-24 16:50:29.079 T:554      info <general>: Default Video Player: VideoPlayer
2023-06-24 16:50:29.079 T:554      info <general>: Default Audio Player: paplayer
2023-06-24 16:50:29.079 T:554      info <general>: Disabled debug logging due to GUI setting. Level 0.
2023-06-24 16:50:29.079 T:554      info <general>: Log level changed to "info"
2023-06-24 16:50:29.079 T:554      info <general>: CMediaSourceSettings: loading media sources from special://masterprofile/sources.xml
2023-06-24 16:50:29.177 T:554      info <general>: creating subdirectories
2023-06-24 16:50:29.178 T:554      info <general>: userdata folder: special://masterprofile/
2023-06-24 16:50:29.178 T:554      info <general>: recording folder:
2023-06-24 16:50:29.178 T:554      info <general>: screenshots folder:
2023-06-24 16:50:29.185 T:554      info <general>: Running database version Addons33
2023-06-24 16:50:30.006 T:676      info <general>: Loading special://xbmc/system/Lircmap.xml
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'mceusb'
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'XboxDVDDongle'
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'Microsoft_Xbox'
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'PinnacleSysPCTVRemote'
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'anysee'
2023-06-24 16:50:30.015 T:676      info <general>: * Adding remote mapping for device 'iMON-PAD'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'Antec_Veris_RM200'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'MCE_via_iMON'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'TwinHanRemote'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'linux-input-layer'
2023-06-24 16:50:30.016 T:676      info <general>: * Linking remote mapping for 'linux-input-layer' to 'cx23885_remote'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'mediacenter'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'devinput'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'devinput-32'
2023-06-24 16:50:30.016 T:676      info <general>: * Adding remote mapping for device 'devinput-64'
2023-06-24 16:50:31.686 T:554   warning <general>: CAddonMgr::FindAddons: Addon 'metadata.tvshows.themoviedb.org.python' already present with higher version 1.6.0 at '/usr/share/kodi/addons/metadata.tvshows.themoviedb.org.python/' - other version 1.4.19 at '/home/osmc/.kodi/addons/metadata.tvshows.themoviedb.org.python/' will be ignored

<... ENUMERATING A BUNCH OF PREINSTALLED ADDONS ...>

2023-06-24 16:50:31.776 T:554      info <general>: Selected Logind/UPower as PowerSyscall
2023-06-24 16:50:31.777 T:554     error <general>: DBus error: org.freedesktop.DBus.Error.ServiceUnknown - The name org.freedesktop.UPower was not provided by any .service files
2023-06-24 16:50:31.777 T:554      info <general>: LogindUPowerSyscall - UPower not found, battery information will not be available
2023-06-24 16:50:31.822 T:554      info <general>: CKeyboardLayoutManager: loading keyboard layouts from special://xbmc/system/keyboardlayouts...
2023-06-24 16:50:31.917 T:554      info <general>: RetroPlayer[RENDER]: Registering renderer factory for DMA
2023-06-24 16:50:31.917 T:554      info <general>: RetroPlayer[RENDER]: Registering renderer factory for OpenGLES
2023-06-24 16:50:31.945 T:554      info <general>: CDRMUtils::FindConnector - using connector: HDMI-A-1
2023-06-24 16:50:31.975 T:554      info <general>: Skipped 1 duplicate messages..
2023-06-24 16:50:31.975 T:554      info <general>: CDRMUtils::FindEncoder - using encoder: 31
2023-06-24 16:50:31.975 T:554      info <general>: CDRMUtils::FindPlanes - using crtc: 94

<ENUMERATING RESOLUTIONS AND REFRESH RATES>

2023-06-24 16:50:32.239 T:554      info <general>: EGL_VERSION = 1.4
2023-06-24 16:50:32.239 T:554      info <general>: EGL_VENDOR = Mesa Project
2023-06-24 16:50:32.239 T:554      info <general>: EGL_EXTENSIONS = EGL_ANDROID_blob_cache EGL_EXT_buffer_age EGL_EXT_image_dma_buf_import EGL_EXT_image_dma_buf_import_modifiers EGL_KHR_cl_event2 EGL_KHR_config_attribs EGL_KHR_create_context EGL_KHR_create_context_no_error EGL_KHR_fence_sync EGL_KHR_get_all_proc_addresses EGL_KHR_gl_colorspace EGL_KHR_gl_renderbuffer_image EGL_KHR_gl_texture_2D_image EGL_KHR_gl_texture_3D_image EGL_KHR_gl_texture_cubemap_image EGL_KHR_image EGL_KHR_image_base EGL_KHR_image_pixmap EGL_KHR_no_config_context EGL_KHR_reusable_sync EGL_KHR_surfaceless_context EGL_EXT_pixel_format_float EGL_KHR_wait_sync EGL_MESA_configless_context EGL_MESA_drm_image EGL_MESA_image_dma_buf_export EGL_MESA_query_driver
2023-06-24 16:50:32.239 T:554      info <general>: EGL_CLIENT_EXTENSIONS = EGL_EXT_client_extensions EGL_EXT_device_base EGL_EXT_device_enumeration EGL_EXT_device_query EGL_EXT_platform_base EGL_KHR_client_get_all_proc_addresses EGL_KHR_debug EGL_EXT_platform_device EGL_MESA_platform_gbm EGL_KHR_platform_gbm EGL_MESA_platform_surfaceless
2023-06-24 16:50:32.257 T:554      info <general>: CApplication::CreateGUI - using the gbm windowing system
2023-06-24 16:50:32.257 T:554      info <general>: Checking resolution 16
2023-06-24 16:50:32.267 T:554      info <general>: GL_VENDOR = Broadcom
2023-06-24 16:50:32.267 T:554      info <general>: GL_RENDERER = V3D 4.2
2023-06-24 16:50:32.267 T:554      info <general>: GL_VERSION = OpenGL ES 3.1 Mesa 20.2.0
2023-06-24 16:50:32.267 T:554      info <general>: GL_SHADING_LANGUAGE_VERSION = OpenGL ES GLSL ES 3.10
2023-06-24 16:50:32.267 T:554      info <general>: GL_EXTENSIONS = GL_EXT_blend_minmax GL_EXT_multi_draw_arrays GL_EXT_texture_compression_s3tc GL_EXT_texture_compression_dxt1 GL_EXT_texture_format_BGRA8888 GL_OES_compressed_ETC1_RGB8_texture GL_OES_depth24 GL_OES_element_index_uint GL_OES_fbo_render_mipmap GL_OES_mapbuffer GL_OES_rgb8_rgba8 GL_OES_standard_derivatives GL_OES_stencil8 GL_OES_texture_3D GL_OES_texture_float GL_OES_texture_half_float GL_OES_texture_half_float_linear GL_OES_texture_npot GL_OES_vertex_half_float GL_EXT_draw_instanced GL_EXT_texture_sRGB_decode GL_OES_EGL_image GL_OES_depth_texture GL_OES_packed_depth_stencil GL_EXT_texture_type_2_10_10_10_REV GL_OES_get_program_binary GL_APPLE_texture_max_level GL_EXT_discard_framebuffer GL_EXT_read_format_bgra GL_EXT_frag_depth GL_NV_fbo_color_attachments GL_OES_EGL_image_external GL_OES_EGL_sync GL_OES_vertex_array_object GL_ANGLE_texture_compression_dxt3 GL_ANGLE_texture_compression_dxt5 GL_EXT_occlusion_query_boolean GL_EXT_texture_rg GL_EXT_unpack_subimage GL_NV_draw_buffers GL_NV_read_buffer GL_NV_read_depth GL_NV_read_depth_stencil GL_NV_read_stencil GL_EXT_draw_buffers GL_EXT_map_buffer_range GL_KHR_debug GL_KHR_texture_compression_astc_ldr GL_NV_pixel_buffer_object GL_OES_depth_texture_cube_map GL_OES_required_internalformat GL_OES_surfaceless_context GL_EXT_color_buffer_float GL_EXT_sRGB_write_control GL_EXT_separate_shader_objects GL_EXT_shader_implicit_conversions GL_EXT_shader_integer_mix GL_EXT_base_instance GL_EXT_compressed_ETC1_RGB8_sub_texture GL_EXT_draw_elements_base_vertex GL_EXT_primitive_bounding_box GL_EXT_shader_io_blocks GL_EXT_texture_border_clamp GL_KHR_context_flush_control GL_NV_image_formats GL_OES_draw_elements_base_vertex GL_OES_primitive_bounding_box GL_OES_shader_io_blocks GL_OES_texture_border_clamp GL_OES_texture_stencil8 GL_OES_texture_storage_multisample_2d_array GL_EXT_buffer_storage GL_EXT_float_blend GL_EXT_geometry_point_size GL_EXT_geometry_shader GL_KHR_no_error GL_KHR_texture_compression_astc_sliced_3d GL_OES_EGL_image_external_essl3 GL_OES_geometry_point_size GL_OES_geometry_shader GL_OES_shader_image_atomic GL_EXT_texture_compression_s3tc_srgb GL_MESA_shader_integer_functions GL_KHR_parallel_shader_compile GL_EXT_EGL_image_storage GL_MESA_framebuffer_flip_y GL_EXT_texture_query_lod
2023-06-24 16:50:32.529 T:554      info <general>: GLES: Maximum texture width: 4096
2023-06-24 16:50:32.530 T:554      info <general>: load keymapping
2023-06-24 16:50:32.532 T:554      info <general>: Loading special://xbmc/system/keymaps/appcommand.xml
2023-06-24 16:50:32.533 T:554      info <general>: Loading special://xbmc/system/keymaps/customcontroller.AppleRemote.xml
2023-06-24 16:50:32.535 T:554      info <general>: Loading special://xbmc/system/keymaps/customcontroller.Harmony.xml
2023-06-24 16:50:32.537 T:554      info <general>: Loading special://xbmc/system/keymaps/customcontroller.SiriRemote.xml
2023-06-24 16:50:32.539 T:554      info <general>: Loading special://xbmc/system/keymaps/gamepad.xml
2023-06-24 16:50:32.541 T:554      info <general>: Loading special://xbmc/system/keymaps/hama_mce.xml
2023-06-24 16:50:32.542 T:554      info <general>: Loading special://xbmc/system/keymaps/joystick.xml
2023-06-24 16:50:32.544 T:554      info <general>: Loading special://xbmc/system/keymaps/keyboard.xml
2023-06-24 16:50:32.549 T:554      info <general>: Loading special://xbmc/system/keymaps/mouse.xml
2023-06-24 16:50:32.550 T:554      info <general>: Loading special://xbmc/system/keymaps/osmc_classic.xml
2023-06-24 16:50:32.551 T:554      info <general>: Loading special://xbmc/system/keymaps/remote.xml
2023-06-24 16:50:32.554 T:554      info <general>: Loading special://xbmc/system/keymaps/touchscreen.xml
2023-06-24 16:50:32.557 T:554      info <general>: Loading special://masterprofile/keymaps/remote.xml
2023-06-24 16:50:32.561 T:554      info <general>: Loading special://profile/keymaps/remote.xml
2023-06-24 16:50:32.563 T:554      info <general>: GUI format 1920x1080, Display 3840x2160 @ 60.000000 Hz
2023-06-24 16:50:32.575 T:802      info <general>: CAESinkALSA::EnumerateDevice - device default description
2023-06-24 16:50:32.593 T:802      info <general>: CAESinkALSA::EnumerateDevice - device sysdefault description Default Audio Device
2023-06-24 16:50:32.599 T:802      info <general>: CAESinkALSA - Unable to open device "bluealsa" for playback
2023-06-24 16:50:32.601 T:802      info <general>: CAESinkALSA - Unable to open device "btaudio" for playback
2023-06-24 16:50:32.602 T:802      info <general>: CAESinkALSA::EnumerateDevice - device sysdefault:CARD=vc4hdmi0 description vc4-hdmi-0, MAI PCM i2s-hifi-0
                                                   Default Audio Device
2023-06-24 16:50:32.603 T:802      info <general>: CAESinkALSA::EnumerateDevice - device hdmi:CARD=vc4hdmi0,DEV=0 description vc4-hdmi-0, MAI PCM i2s-hifi-0
                                                   HDMI Audio Output
2023-06-24 16:50:32.604 T:802      info <general>: CAESinkALSA - Unable to open device "sysdefault:CARD=vc4hdmi1" for playback
2023-06-24 16:50:32.605 T:802      info <general>: CAESinkALSA - Unable to open device "hdmi:CARD=vc4hdmi1,DEV=0" for playback
2023-06-24 16:50:32.606 T:802      info <general>: CAESinkALSA::EnumerateDevice - device sysdefault:CARD=sndrpihifiberry description snd_rpi_hifiberry_dacplus, HiFiBerry DAC+ Pro HiFi pcm512x-hifi-0
                                                   Default Audio Device
2023-06-24 16:50:32.607 T:802      info <general>: Found 1 Lists of Devices
2023-06-24 16:50:32.607 T:802      info <general>: Enumerated ALSA devices:

<TRIMMED>

2023-06-24 16:52:34.554 T:554      info <general>: Loading skin file: Settings.xml, load type: KEEP_IN_MEMORY
2023-06-24 16:52:38.092 T:554      info <general>: Loading skin file: /usr/share/kodi/addons/service.osmc.settings/resources/skins/Default/1080i/settings_gui_720.xml, load type: LOAD_ON_GUI_INIT
2023-06-24 16:52:38.221 T:821     error <general>: EXCEPTION: Non-Existent Control 300
2023-06-24 16:52:40.518 T:554      info <general>: Loading skin file: /usr/share/kodi/addons/script.module.osmcsetting.networking/resources/skins/Default/1080i/network_gui.xml, load type: LOAD_ON_GUI_INIT
2023-06-24 16:52:40.776 T:985     error <general>: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                                    - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                                   Error Type: <class 'PermissionError'>
                                                   Error Contents: [Errno 13] Permission denied: '/etc/default/crda'
                                                   Traceback (most recent call last):
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 359, in onInit
                                                       self.set_crda_region_code()
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 1838, in set_crda_region_code
                                                       self._set_crda_region_code()
                                                     File "/usr/share/kodi/addons/script.module.osmcsetting.networking/resources/lib/osmcnetworking/networking_gui.py", line 1827, in _set_crda_region_code
                                                       with open(self._crda_file, 'w', encoding='utf-8') as file_handle:
                                                   PermissionError: [Errno 13] Permission denied: '/etc/default/crda'
                                                   -->End of Python script error report<--

2023-06-24 16:52:43.083 T:554      info <general>: Loading skin file: DialogSelect.xml, load type: KEEP_IN_MEMORY
2023-06-24 16:52:52.279 T:817      info <general>: AddOnLog: peripheral.joystick: Initialized joystick 0: "Wireless Controller", axes: 8, hats: 0, buttons: 13
2023-06-24 16:52:52.279 T:817      info <general>: Loading controller layout: /home/osmc/.kodi/addons/game.controller.default/resources/layout.xml
2023-06-24 16:52:52.301 T:817      info <general>: Loading controller layout: /usr/share/kodi/addons/game.controller.mouse/resources/layout.xml
2023-06-24 16:52:52.327 T:817      info <general>: Loading controller layout: /home/osmc/.kodi/addons/game.controller.ps.dualshock/resources/layout.xml
2023-06-24 16:52:52.430 T:817      info <general>: Register - new joystick device registered on addon->peripheral.joystick/0: Wireless Controller
2023-06-24 16:52:54.952 T:802      info <general>: CAESinkALSA::EnumerateDevice - device default description
2023-06-24 16:52:54.970 T:802      info <general>: CAESinkALSA::EnumerateDevice - device sysdefault description Default Audio Device
2023-06-24 16:52:54.973 T:802      info <general>: CAESinkALSA - Unable to open device "bluealsa" for playback
2023-06-24 16:52:54.975 T:802      info <general>: CAESinkALSA - Unable to open device "btaudio" for playback
2023-06-24 16:52:54.988 T:803      info <general>: CAESinkALSA::InitializeHW - Your hardware does not support AE_FMT_FLOAT, trying other formats
2023-06-24 16:52:54.988 T:803      info <general>: CAESinkALSA::InitializeHW - Using data format AE_FMT_S24NE3
2023-06-24 16:53:04.738 T:554      info <general>: Loading skin file: MyGames.xml, load type: KEEP_IN_MEMORY
2023-06-24 16:53:09.238 T:554      info <general>: Loading skin file: MyFavourites.xml, load type: KEEP_IN_MEMORY
2023-06-24 16:53:12.213 T:554     error <general>: GetItemsForPlayList: Unable to get playlist items for plugin://plugin.program.moonlight-qt/?mode=launch
2023-06-24 16:53:12.731 T:1037  warning <general>: Failed to resolve audio output device, audio within Moonlight might not work: [Errno 13] Permission denied: '/home/osmc/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.config/alsa/asoundrc'
2023-06-24 16:53:12.731 T:1037     info <general>: Launching moonlight-qt: systemd-run --setenv=ADDON_PROFILE_PATH="/home/osmc/.kodi/userdata/addon_data/plugin.program.moonlight-qt" --setenv=PULSE_SERVER="none" --setenv=SDL_AUDIODRIVER="alsa" bash /home/osmc/.kodi/addons/plugin.program.moonlight-qt/resources/bin/launch_moonlight-qt.sh
2023-06-24 16:53:12.739 T:554      info <general>: Loading skin file: DialogConfirm.xml, load type: KEEP_IN_MEMORY
2023-06-24 16:53:13.455 T:554      info <general>: Quitting due to POSIX signal
2023-06-24 16:53:13.472 T:554      info <general>: Stopping the application...
2023-06-24 16:53:13.472 T:554      info <general>: Stopping player
2023-06-24 16:53:13.472 T:554      info <general>: Stopping all
2023-06-24 16:53:13.472 T:554      info <general>: ES: Stopping event server
2023-06-24 16:53:14.430 T:822      info <general>: ES: UDP Event server stopped
2023-06-24 16:53:15.770 T:554      info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2023-06-24 16:53:15.771 T:554      info <CWebserver[80]>: Stopped
2023-06-24 16:53:15.772 T:819      info <general>: [Audio Profiles Service] background monitor version 2.1.2 stopped
2023-06-24 16:53:15.789 T:820      info <general>: CPythonInvoker(1, /usr/share/kodi/addons/script.module.osmcsetting.updates/resources/lib/service.py): waiting on thread 3674431744
2023-06-24 16:53:15.947 T:821      info <general>: CPythonInvoker(2, /usr/share/kodi/addons/service.osmc.settings/resources/lib/service.py): waiting on thread 3658477824
2023-06-24 16:53:16.390 T:554      info <general>: Application stopped
2023-06-24 16:53:17.316 T:554      info <general>: AddOnLog: peripheral.joystick: Disabling joystick interface "linux"
2023-06-24 16:53:17.316 T:554      info <general>: ADDON: Dll Destroyed - Joystick Support
2023-06-24 16:53:17.316 T:554      info <general>: unload skin
2023-06-24 16:53:17.389 T:554      info <general>: Unloaded skin
2023-06-24 16:53:17.408 T:554      info <general>: unload sections
2023-06-24 16:53:17.425 T:554      info <general>: CWSDiscoveryListenerUDP::Stop - Stopped
2023-06-24 16:53:17.760 T:554      info <general>: Exiting the application...
```

**Comment by veldenb** [comment]
It looks like the plugin has no write access to it's files:
```
2023-06-24 16:53:12.731 T:1037  warning <general>: Failed to resolve audio output device, audio within Moonlight might not work: [Errno 13] Permission denied: '/home/osmc/.kodi/userdata/addon_data/plugin.program.moonlight-qt/moonlight-home/.config/alsa/asoundrc'
2
```
Maybe something is wrong with the file permissions on your system?

**Comment by kurac338** [comment]
I've just tried reinstalling the addon. That file was not recreated.
The new structure looks like this:
``` shell
osmc@osmc:~$ cd .kodi/userdata/addon_data/plugin.program.moonlight-qt/

osmc@osmc:~/.kodi/userdata/addon_data/plugin.program.moonlight-qt$ ls -la ../
total 64
drwx------ 16 osmc osmc 4096 Jun 25 17:04 .
drwxr-xr-x 10 osmc osmc 4096 Jun 24 17:08 ..
drwxr-xr-x  2 osmc osmc 4096 Sep 29  2022 metadata.themoviedb.org.python
drwx------  2 osmc osmc 4096 Sep 28  2022 metadata.tvshows.themoviedb.org.python
drwx------  3 osmc osmc 4096 Sep 18  2022 peripheral.joystick
drwx------  3 osmc osmc 4096 Sep 28  2022 plugin.audio.radio_de
drwxr-xr-x  4 osmc osmc 4096 Jun 25 17:05 plugin.program.moonlight-qt
drwx------  2 osmc osmc 4096 Sep 28  2022 screensaver.bing
drwx------  2 osmc osmc 4096 Sep 28  2022 script.audio.profiles
drwxr-xr-x  2 osmc osmc 4096 Sep 28  2022 script.module.osmcsetting.apfstore
drwx------  2 osmc osmc 4096 Sep 18  2022 script.module.osmcsetting.pi
drwx------  2 osmc osmc 4096 Sep 27  2022 script.module.osmcsetting.updates
drwx------  2 osmc osmc 4096 Jun 25 17:07 script.module.simplecache
drwx------  3 osmc osmc 4096 Jun  8 20:08 service.subtitles.opensubtitles
drwx------  2 osmc osmc 4096 Sep 18  2022 skin.osmc
drwx------  2 osmc osmc 4096 Sep 28  2022 weather.multi

osmc@osmc:~/.kodi/userdata/addon_data/plugin.program.moonlight-qt$ ls -la 
total 104
drwxr-xr-x  4 osmc osmc  4096 Jun 25 17:05 .
drwx------ 16 osmc osmc  4096 Jun 25 17:04 ..
drwxr-xr-x  4 root root  4096 Jun 25 17:05 moonlight-home
drwxr-xr-x  3 osmc osmc  4096 Jun 25 17:05 moonlight-qt
-rw-r--r--  1 root root 89016 Jun 25 17:19 moonlight-qt.log

osmc@osmc:~/.kodi/userdata/addon_data/plugin.program.moonlight-qt$ ls -la moonlight-home/.config/
total 12
drwxr-xr-x 3 root root 4096 Jun 25 17:05  .
drwxr-xr-x 4 root root 4096 Jun 25 17:05  ..
drwxr-xr-x 2 root root 4096 Jun 25 17:19 'Moonlight Game Streaming Project'
```
However the missing icon issue persists :(

**Comment by veldenb** [comment]
Can you install this version of the plugin and run `chown -R osmc:osmc moonlight-home` before retrying?
[plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/11860466/plugin.program.moonlight-qt-main.zip)

It should do a better check if moonlight should be run as root or a normal user.

**Comment by kurac338** [comment]
It fails to start the app.
I can see in the Kodi logs that it picked up the new `--user` flag:
`2023-06-25 20:18:35.489 T:2075    error <general>: Launching moonlight-qt failed: systemd-run --user --setenv=ADDON_PROFILE_PATH="/home/osmc/.kodi/userdata/addon_data/plugin.program.moonlight-qt" --setenv=PULSE_SERVER="none" --setenv=SDL_AUDIODRIVER="alsa" bash /home/osmc/.kodi/addons/plugin.program.moonlight-qt/resources/bin/launch_moonlight-qt.sh `

**Comment by veldenb** [comment]
Hard to tell what goes wrong, probably need to install OSMC myself to debug this.

**Comment by veldenb** [comment]
I made some changes so moonlight is started under the osmc user and made audio detection somewhat more robust. Can you give this build a spin? [plugin.program.moonlight-qt-main.zip](https://github.com/veldenb/plugin.program.moonlight-qt/files/11861281/plugin.program.moonlight-qt-main.zip)

The problem in the Games menu seems to be a skin issue. When I switch from the OSMC-Skin to the Estuary skin the menu starts working. So I think it's an OSMC bug.

**Comment by veldenb** [comment]
Command looks as expected :+1:
